---

- hosts: group1
  
  tasks:
  
    - name: Ensure nginx is installed
      yum: name=nginx
      
    - name: Ensure nginx is started
      service: name=nginx state=started
      
- hosts: group2

  tasks:
  
    - name: Ensure httpd is installed
      yum: name=httpd